server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /auth-api/ {
        proxy_pass http://auth:8080/;
    }

    location /api/ {
        client_max_body_size 16m;
        proxy_pass http://api-backend:8080/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
